; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra strings
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
src_filter = -<*> +<bmp585_test.cpp> +<main.cpp>
lib_extra_dirs = ${PROJECT_DIR}/lib
lib_deps =
  pololu/VL53L0X @ ^1.3.1
  https://github.com/DFRobot/DFRobot_RTU.git
  https://github.com/DFRobot/DFRobot_BMP58X.git#master
; Replace COM3 with your actual ESP32 port
; upload_port = COM3
; monitor_port = COM3
